name: Code quality checker

env:
  S3_DEPLOY_BUCKET_NAME: "bb-site-deployments"
  AWS_REGION_NAME: "eu-central-1"
  DEPLOY_BUILD_NAME: "bb_${{ github.head_ref }}"
  
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
    
      - name: Copy Build to S3 bucket
        run: aws s3 cp ./ s3://${{ env.S3_DEPLOY_BUCKET_NAME }}/${{ env.DEPLOY_BUILD_NAME }} --recursive --exclude ".git/*"
        
      - name: Invalidate CDN Cache of build
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWF_CF_DISTRIBUTION_ID }} --paths "/${{ env.DEPLOY_BUILD_NAME }}/*"
